version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
    depends_on:
      - backend-feed
      - backend-user
      - frontend
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend
    ports:
      - "8100:80"
  backend-user:
    env_file:
      - variables.env
    build:
      context: ./udagram-api-user
    image: udagram-api-user
    # ports:
    #   - "8081:8081"
  backend-feed:
    env_file:
      - variables.env
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    # ports:
    #   - "8082:8082"